In [19]:
import pandas as pd

df = pd.read_csv("final_food_delivery_dataset.csv")
df.head()

,order_id,user_id,restaurant_id,order_date,total_amount,restaurant_name_x,name,city,membership,restaurant_name_y,cuisine,rating
0,1,2508,450,18-02-2023,842.97,New Foods Chinese,User_2508,Hyderabad,Regular,Restaurant_450,Mexican,3.2
1,2,2693,309,18-01-2023,546.68,Ruchi Curry House Multicuisine,User_2693,Pune,Regular,Restaurant_309,Indian,4.5
2,3,2084,107,15-07-2023,163.93,Spice Kitchen Punjabi,User_2084,Chennai,Gold,Restaurant_107,Mexican,4.0
3,4,319,224,04-10-2023,1155.97,Darbar Kitchen Non-Veg,User_319,Bangalore,Gold,Restaurant_224,Chinese,4.8
4,5,1064,293,25-12-2023,1321.91,Royal Eatery South Indian,User_1064,Pune,Regular,Restaurant_293,Italian,3.0

In [59]:
df.columns

Index(['order_id', 'user_id', 'restaurant_id', 'order_date', 'total_amount',
       'restaurant_name_x', 'name', 'city', 'membership', 'restaurant_name_y',
       'cuisine', 'rating'],
      dtype='object')

In [89]:
['order_id', 'user_id', 'restaurant_id', 'cuisine', 'total_amount', ...]

['order_id', 'user_id', 'restaurant_id', 'cuisine', 'total_amount', Ellipsis]

In [90]:
avg_order = df.groupby('cuisine')['total_amount'].mean()
avg_order

cuisine
Chinese    798.389020
Indian     798.466011
Italian    799.448578
Mexican    808.021344
Name: total_amount, dtype: float64

In [91]:
avg_order.sort_values(ascending=False).head(1)

cuisine
Mexican    808.021344
Name: total_amount, dtype: float64

In [92]:
user_total = df.groupby('user_id')['total_amount'].sum()
user_total

user_id
1       1289.66
2       7564.12
3       1839.51
4       3741.16
5       5742.88
         ...
2996    1533.54
2997    5310.32
2998    4241.47
2999     643.89
3000    2226.63
Name: total_amount, Length: 2883, dtype: float64

In [93]:
high_value_users = user_total[user_total > 1000]
high_value_users

user_id
1       1289.66
2       7564.12
3       1839.51
4       3741.16
5       5742.88
         ...
2995    2472.66
2996    1533.54
2997    5310.32
2998    4241.47
3000    2226.63
Name: total_amount, Length: 2544, dtype: float64

In [94]:
high_value_users.count()

np.int64(2544)

In [95]:
# Create rating ranges
df['rating_range'] = pd.cut(
    df['rating'],
    bins=[0, 2, 3, 4, 5],
    labels=['0–2', '2–3', '3–4', '4–5']
)

df[['rating', 'rating_range']].head()

   rating rating_range
0     3.2          3–4
1     4.5          4–5
2     4.0          3–4
3     4.8          4–5
4     3.0          2–3

In [96]:
rating_revenue = df.groupby('rating_range')['total_amount'].sum()
rating_revenue

C:\Users\ruchi\AppData\Local\Temp\ipykernel_23776\3029047093.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  rating_revenue = df.groupby('rating_range')['total_amount'].sum()

rating_range
0–2          0.00
2–3     255018.13
3–4    3599248.98
4–5    4157357.01
Name: total_amount, dtype: float64

In [99]:
gold_df = df[df['membership'] == 'Gold']

In [100]:
gold_df.groupby('city')['total_amount'].mean().sort_values(ascending=False).head(1)

city
Chennai    808.45908
Name: total_amount, dtype: float64

In [101]:
restaurant_count = df.groupby('cuisine')['restaurant_id'].nunique()
restaurant_count

cuisine
Chinese    120
Indian     126
Italian    126
Mexican    128
Name: restaurant_id, dtype: int64

In [102]:
revenue_per_cuisine = df.groupby('cuisine')['total_amount'].sum()
revenue_per_cuisine

cuisine
Chinese    1930504.65
Indian     1971412.58
Italian    2024203.80
Mexican    2085503.09
Name: total_amount, dtype: float64

In [103]:
summary = pd.concat([restaurant_count, revenue_per_cuisine], axis=1)
summary.columns = ['distinct_restaurants', 'total_revenue']
summary

         distinct_restaurants  total_revenue
cuisine
Chinese                   120     1930504.65
Indian                    126     1971412.58
Italian                   126     2024203.80
Mexican                   128     2085503.09

In [105]:
df.columns

Index(['order_id', 'user_id', 'restaurant_id', 'order_date', 'total_amount',
       'restaurant_name_x', 'name', 'city', 'membership', 'restaurant_name_y',
       'cuisine', 'rating', 'quarter', 'rating_range'],
      dtype='object')

In [106]:
total_orders = df.shape[0]
total_orders

10000

In [109]:
df.columns.tolist()

['order_id',
 'user_id',
 'restaurant_id',
 'order_date',
 'total_amount',
 'restaurant_name_x',
 'name',
 'city',
 'membership',
 'restaurant_name_y',
 'cuisine',
 'rating',
 'quarter',
 'rating_range']

In [110]:
for col in df.columns:
    print(col, df[col].unique()[:5])

order_id [1 2 3 4 5]
user_id [2508 2693 2084  319 1064]
restaurant_id [450 309 107 224 293]
order_date <DatetimeArray>
['2023-02-18 00:00:00', '2023-01-18 00:00:00', '2023-07-15 00:00:00',
 '2023-10-04 00:00:00', '2023-12-25 00:00:00']
Length: 5, dtype: datetime64[ns]
total_amount [ 842.97  546.68  163.93 1155.97 1321.91]
restaurant_name_x ['New Foods Chinese' 'Ruchi Curry House Multicuisine'
 'Spice Kitchen Punjabi' 'Darbar Kitchen Non-Veg'
 'Royal Eatery South Indian']
name ['User_2508' 'User_2693' 'User_2084' 'User_319' 'User_1064']
city ['Hyderabad' 'Pune' 'Chennai' 'Bangalore']
membership ['Regular' 'Gold']
restaurant_name_y ['Restaurant_450' 'Restaurant_309' 'Restaurant_107' 'Restaurant_224'
 'Restaurant_293']
cuisine ['Mexican' 'Indian' 'Chinese' 'Italian']
rating [3.2 4.5 4.  4.8 3. ]
quarter [1 3 4 2]
rating_range ['3–4', '4–5', '2–3']
Categories (4, object): ['0–2' < '2–3' < '3–4' < '4–5']

In [112]:
total_orders = df.shape[0]
total_orders

10000

In [113]:
gold_orders = df[df['membership'] == 'Gold'].shape[0]
gold_orders

4987

In [114]:

percentage_gold_orders = round((gold_orders / total_orders) * 100)
percentage_gold_orders

50

In [115]:
order_counts = df.groupby('restaurant_name_x')['order_id'].count()
order_counts.head()

restaurant_name_x
Amma Biryani Family Restaurant    45
Amma Biryani North Indian         57
Amma Biryani South Indian         15
Amma Cafe Non-Veg                 24
Amma Cafe North Indian            11
Name: order_id, dtype: int64

In [116]:
restaurants_less_20 = order_counts[order_counts < 20].index
restaurants_less_20

Index(['Amma Biryani South Indian', 'Amma Cafe North Indian',
       'Amma Cafe Pure Veg', 'Amma Curry House Family Restaurant',
       'Amma Delights Family Restaurant', 'Amma Dhaba Non-Veg',
       'Amma Dhaba Punjabi', 'Amma Kitchen Pure Veg', 'Amma Mess Punjabi',
       'Amma Mess Pure Veg',
       ...
       'Udupi Curry House Andhra', 'Udupi Delights Family Restaurant',
       'Udupi Dhaba Non-Veg', 'Udupi Dhaba Pure Veg',
       'Udupi Kitchen Multicuisine', 'Udupi Mess Family Restaurant',
       'Udupi Mess North Indian', 'Udupi Restaurant Family Restaurant',
       'Udupi Restaurant Pure Veg', 'Udupi Restaurant South Indian'],
      dtype='object', name='restaurant_name_x', length=170)

In [117]:
avg_order_value = df[df['restaurant_name_x'].isin(restaurants_less_20)].groupby('restaurant_name_x')['total_amount'].mean()
avg_order_value

restaurant_name_x
Amma Biryani South Indian             708.708667
Amma Cafe North Indian                667.979091
Amma Cafe Pure Veg                    839.633529
Amma Curry House Family Restaurant    821.800556
Amma Delights Family Restaurant       761.249412
                                         ...
Udupi Mess Family Restaurant          831.023125
Udupi Mess North Indian               898.528125
Udupi Restaurant Family Restaurant    796.961053
Udupi Restaurant Pure Veg             895.619000
Udupi Restaurant South Indian         828.162778
Name: total_amount, Length: 170, dtype: float64

In [118]:
top_restaurant = avg_order_value.sort_values(ascending=False).head(1)
top_restaurant

restaurant_name_x
Hotel Dhaba Multicuisine    1040.222308
Name: total_amount, dtype: float64

In [119]:
options = ['Grand Cafe Punjabi', 'Grand Restaurant South Indian', 'Ruchi Mess Multicuisine', 'Ruchi Foods Chinese']
avg_order_value_options = avg_order_value[avg_order_value.index.isin(options)]
avg_order_value_options.sort_values(ascending=False).head(1)

restaurant_name_x
Ruchi Foods Chinese    686.603158
Name: total_amount, dtype: float64

In [121]:
top_combo = combo_revenue.sort_values(ascending=False).head(1)
top_combo

membership  cuisine
Regular     Mexican    1072943.3
Name: total_amount, dtype: float64

In [120]:
combo_revenue = df.groupby(['membership', 'cuisine'])['total_amount'].sum()
combo_revenue

membership  cuisine
Gold        Chinese     977713.74
            Indian      979312.31
            Italian    1005779.05
            Mexican    1012559.79
Regular     Chinese     952790.91
            Indian      992100.27
            Italian    1018424.75
            Mexican    1072943.30
Name: total_amount, dtype: float64

In [122]:
options = [
    ('Gold', 'Indian'),
    ('Gold', 'Italian'),
    ('Regular', 'Indian'),
    ('Regular', 'Chinese')
]

combo_revenue_options = combo_revenue.loc[options]
combo_revenue_options

membership  cuisine
Gold        Indian      979312.31
            Italian    1005779.05
Regular     Indian      992100.27
            Chinese     952790.91
Name: total_amount, dtype: float64

In [123]:
top_combo = combo_revenue_options.sort_values(ascending=False).head(1)
top_combo

membership  cuisine
Gold        Italian    1005779.05
Name: total_amount, dtype: float64

In [124]:
df['order_date'] = pd.to_datetime(df['order_date'], format='%d-%m-%Y')
df['order_date'].head()

0   2023-02-18
1   2023-01-18
2   2023-07-15
3   2023-10-04
4   2023-12-25
Name: order_date, dtype: datetime64[ns]

In [125]:
df['quarter'] = df['order_date'].dt.quarter
df[['order_date', 'quarter']].head()

  order_date  quarter
0 2023-02-18        1
1 2023-01-18        1
2 2023-07-15        3
3 2023-10-04        4
4 2023-12-25        4

In [126]:
revenue_per_quarter = df.groupby('quarter')['total_amount'].sum()
revenue_per_quarter

quarter
1    2010626.64
2    1945348.72
3    2037385.10
4    2018263.66
Name: total_amount, dtype: float64

In [127]:
top_quarter = revenue_per_quarter.sort_values(ascending=False).head(1)
top_quarter

quarter
3    2037385.1
Name: total_amount, dtype: float64

In [128]:
gold_orders = df[df['membership'] == 'Gold'].shape[0]
gold_orders

4987

In [129]:
hyderabad_orders = df[df['city'] == 'Hyderabad']

In [131]:
total_revenue_hyderabad = round(total_revenue_hyderabad)
total_revenue_hyderabad

1889367

In [132]:
distinct_users = df['user_id'].nunique()
distinct_users

2883

In [133]:
gold_orders = df[df['membership'] == 'Gold']

In [134]:
avg_order_value_gold = gold_orders['total_amount'].mean()
round(avg_order_value_gold, 2)

np.float64(797.15)

In [135]:
high_rating_orders = df[df['rating'] >= 4.5]

In [136]:
total_high_rating_orders = high_rating_orders.shape[0]
total_high_rating_orders

3374

In [137]:
revenue_per_city_gold = gold_orders.groupby('city')['total_amount'].sum()
revenue_per_city_gold

city
Bangalore     994702.59
Chennai      1080909.79
Hyderabad     896740.19
Pune         1003012.32
Name: total_amount, dtype: float64

In [138]:
top_city = revenue_per_city_gold.sort_values(ascending=False).head(1).index[0]
top_city

'Chennai'

In [139]:
# Total number of rows
total_rows = df.shape[0]
total_rows

10000